# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import blockchain_pb2 as blockchain__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nauth.proto\x1a\x10\x62lockchain.proto\"\x83\x01\n\x0bVerifyTxReq\x12\x19\n\x11valid_until_block\x18\x01 \x01(\x04\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x17\n\x06\x63rypto\x18\x04 \x01(\x0e\x32\x07.Crypto\x12\x0f\n\x07tx_hash\x18\x05 \x01(\x0c\x12\x0e\n\x06signer\x18\x06 \x01(\x0c\"B\n\x0cVerifyTxResp\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\x12\x11\n\x03ret\x18\x02 \x01(\x0e\x32\x04.Ret\x12\x0e\n\x06signer\x18\x03 \x01(\x0c\"8\n\x0eVerifyBlockReq\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1a\n\x04reqs\x18\x02 \x03(\x0b\x32\x0c.VerifyTxReq\"0\n\x0fVerifyBlockResp\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\x03ret\x18\x02 \x01(\x0e\x32\x04.Ret\"2\n\rBlockTxHashes\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x11\n\ttx_hashes\x18\x02 \x03(\x0c\"\"\n\x10\x42lockTxHashesReq\x12\x0e\n\x06height\x18\x01 \x01(\x04*H\n\x03Ret\x12\x06\n\x02Ok\x10\x00\x12\x07\n\x03\x45rr\x10\x01\x12\x07\n\x03\x44up\x10\x02\x12\r\n\tOutOfTime\x10\x03\x12\n\n\x06\x42\x61\x64Sig\x10\x04\x12\x0c\n\x08NotReady\x10\x05\x62\x06proto3')
  ,
  dependencies=[blockchain__pb2.DESCRIPTOR,])

_RET = _descriptor.EnumDescriptor(
  name='Ret',
  full_name='Ret',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ok', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Err', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Dup', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OutOfTime', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BadSig', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotReady', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=430,
  serialized_end=502,
)
_sym_db.RegisterEnumDescriptor(_RET)

Ret = enum_type_wrapper.EnumTypeWrapper(_RET)
Ok = 0
Err = 1
Dup = 2
OutOfTime = 3
BadSig = 4
NotReady = 5



_VERIFYTXREQ = _descriptor.Descriptor(
  name='VerifyTxReq',
  full_name='VerifyTxReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid_until_block', full_name='VerifyTxReq.valid_until_block', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hash', full_name='VerifyTxReq.hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='VerifyTxReq.signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crypto', full_name='VerifyTxReq.crypto', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='VerifyTxReq.tx_hash', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signer', full_name='VerifyTxReq.signer', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=164,
)


_VERIFYTXRESP = _descriptor.Descriptor(
  name='VerifyTxResp',
  full_name='VerifyTxResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='VerifyTxResp.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='VerifyTxResp.ret', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signer', full_name='VerifyTxResp.signer', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=232,
)


_VERIFYBLOCKREQ = _descriptor.Descriptor(
  name='VerifyBlockReq',
  full_name='VerifyBlockReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VerifyBlockReq.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqs', full_name='VerifyBlockReq.reqs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=290,
)


_VERIFYBLOCKRESP = _descriptor.Descriptor(
  name='VerifyBlockResp',
  full_name='VerifyBlockResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VerifyBlockResp.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='VerifyBlockResp.ret', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=340,
)


_BLOCKTXHASHES = _descriptor.Descriptor(
  name='BlockTxHashes',
  full_name='BlockTxHashes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='BlockTxHashes.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_hashes', full_name='BlockTxHashes.tx_hashes', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=392,
)


_BLOCKTXHASHESREQ = _descriptor.Descriptor(
  name='BlockTxHashesReq',
  full_name='BlockTxHashesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='BlockTxHashesReq.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=428,
)

_VERIFYTXREQ.fields_by_name['crypto'].enum_type = blockchain__pb2._CRYPTO
_VERIFYTXRESP.fields_by_name['ret'].enum_type = _RET
_VERIFYBLOCKREQ.fields_by_name['reqs'].message_type = _VERIFYTXREQ
_VERIFYBLOCKRESP.fields_by_name['ret'].enum_type = _RET
DESCRIPTOR.message_types_by_name['VerifyTxReq'] = _VERIFYTXREQ
DESCRIPTOR.message_types_by_name['VerifyTxResp'] = _VERIFYTXRESP
DESCRIPTOR.message_types_by_name['VerifyBlockReq'] = _VERIFYBLOCKREQ
DESCRIPTOR.message_types_by_name['VerifyBlockResp'] = _VERIFYBLOCKRESP
DESCRIPTOR.message_types_by_name['BlockTxHashes'] = _BLOCKTXHASHES
DESCRIPTOR.message_types_by_name['BlockTxHashesReq'] = _BLOCKTXHASHESREQ
DESCRIPTOR.enum_types_by_name['Ret'] = _RET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerifyTxReq = _reflection.GeneratedProtocolMessageType('VerifyTxReq', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYTXREQ,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:VerifyTxReq)
  ))
_sym_db.RegisterMessage(VerifyTxReq)

VerifyTxResp = _reflection.GeneratedProtocolMessageType('VerifyTxResp', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYTXRESP,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:VerifyTxResp)
  ))
_sym_db.RegisterMessage(VerifyTxResp)

VerifyBlockReq = _reflection.GeneratedProtocolMessageType('VerifyBlockReq', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYBLOCKREQ,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:VerifyBlockReq)
  ))
_sym_db.RegisterMessage(VerifyBlockReq)

VerifyBlockResp = _reflection.GeneratedProtocolMessageType('VerifyBlockResp', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYBLOCKRESP,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:VerifyBlockResp)
  ))
_sym_db.RegisterMessage(VerifyBlockResp)

BlockTxHashes = _reflection.GeneratedProtocolMessageType('BlockTxHashes', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKTXHASHES,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:BlockTxHashes)
  ))
_sym_db.RegisterMessage(BlockTxHashes)

BlockTxHashesReq = _reflection.GeneratedProtocolMessageType('BlockTxHashesReq', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKTXHASHESREQ,
  __module__ = 'auth_pb2'
  # @@protoc_insertion_point(class_scope:BlockTxHashesReq)
  ))
_sym_db.RegisterMessage(BlockTxHashesReq)


# @@protoc_insertion_point(module_scope)
