# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x63ommunication.proto\"q\n\x07Message\x12\x0e\n\x06\x63md_id\x18\x01 \x01(\r\x12\x16\n\x04type\x18\x02 \x01(\x0e\x32\x08.MsgType\x12\x0e\n\x06origin\x18\x03 \x01(\r\x12\x1d\n\x07operate\x18\x04 \x01(\x0e\x32\x0c.OperateType\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c*\xef\x01\n\x07MsgType\x12\x0b\n\x07REQUEST\x10\x00\x12\n\n\x06HEADER\x10\x01\x12\x08\n\x04\x42ODY\x10\x02\x12\t\n\x05\x42LOCK\x10\x03\x12\x06\n\x02TX\x10\x04\x12\n\n\x06STATUS\x10\x05\x12\x07\n\x03MSG\x10\x06\x12\x0c\n\x08RESPONSE\x10\x07\x12\x0f\n\x0bTX_RESPONSE\x10\x08\x12\x11\n\rVERIFY_TX_REQ\x10\t\x12\x12\n\x0eVERIFY_TX_RESP\x10\n\x12\x12\n\x0eVERIFY_BLK_REQ\x10\x0b\x12\x13\n\x0fVERIFY_BLK_RESP\x10\x0c\x12\x12\n\x0e\x42LOCK_TXHASHES\x10\r\x12\x16\n\x12\x42LOCK_TXHASHES_REQ\x10\x0e*6\n\x0bOperateType\x12\r\n\tBROADCAST\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x0c\n\x08SUBTRACT\x10\x02\x62\x06proto3')
)

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEADER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BODY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TX', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TX_RESPONSE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_TX_REQ', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_TX_RESP', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_BLK_REQ', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_BLK_RESP', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_TXHASHES', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_TXHASHES_REQ', index=14, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

MsgType = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
_OPERATETYPE = _descriptor.EnumDescriptor(
  name='OperateType',
  full_name='OperateType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BROADCAST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBTRACT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_OPERATETYPE)

OperateType = enum_type_wrapper.EnumTypeWrapper(_OPERATETYPE)
REQUEST = 0
HEADER = 1
BODY = 2
BLOCK = 3
TX = 4
STATUS = 5
MSG = 6
RESPONSE = 7
TX_RESPONSE = 8
VERIFY_TX_REQ = 9
VERIFY_TX_RESP = 10
VERIFY_BLK_REQ = 11
VERIFY_BLK_RESP = 12
BLOCK_TXHASHES = 13
BLOCK_TXHASHES_REQ = 14
BROADCAST = 0
SINGLE = 1
SUBTRACT = 2



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_id', full_name='Message.cmd_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='Message.origin', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operate', full_name='Message.operate', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Message.content', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=136,
)

_MESSAGE.fields_by_name['type'].enum_type = _MSGTYPE
_MESSAGE.fields_by_name['operate'].enum_type = _OPERATETYPE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['MsgType'] = _MSGTYPE
DESCRIPTOR.enum_types_by_name['OperateType'] = _OPERATETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
